[[action]]
return="database"
[action.operation]
key="database"
type="temporary"
value="gufengmh8_page"


[[action]]
return="url"
[action.target]
key="url"
type="string"
value="https://www.gufengmh8.com/manhua/woweicangsheng/1207509.html"
[action.operation]
key="html"
type="download"
[action.after]
[action.after.transform]
target="html"
from="gbk"
to="utf8"
[action.after.replace]
target="html"
from="<img{^>}+src=\"({^\"}+)\"{^>}+data-original=\"({^\"}+)\">"
to="<img src=\"$1\" data-original=\"$2\">"


[[action]]
return="code"
[action.target]
key="url"
type="temp"
[action.operation]
key="code"
type="regex_get"
value="://\\w+\\.(\\w+)\\.\\w+"


[[action]]
[action.target]
key="html"
type="temp"
[action.operation]
key="dom"
type="dom_parser"


[[action]]
return="title"
[action.target]
key="dom"
type="temp"
[action.operation]
key="title"
type="dom_find"
value=".chapter-view h2"


[[action]]
return="number"
[action.target]
key="html"
type="temp"
[action.operation]
key="number"
type="regex_get"
value="comic\\.(\\d+)"


[[action]]
return="chapter"
[action.target]
key="url"
type="temp"
[action.operation]
key="chapter"
type="regex_get"
value="(\\w+)\\.html"

[[action]]
[action.target]
key="html"
type="temp"
[action.operation]
key="imagePath"
type="regex_get"
value="var chapterPath\\s?=\\s?\"([^\"]+)\""


[[action]]
[action.target]
key="html"
type="temp"
[action.operation]
key="imgsStr"
type="regex_get"
value="var chapterImages\\s?=\\s?\\[([^\\]]+)\\]"
[action.after]
[action.after.replace]
target="imgsStr"
from="\""
to=""

[[action]]
[action.target]
key="imgsStr"
type="temp"
value=""
[action.operation]
key="imgs"
type="strings_Split"
value=","
[action.after]
[action.after.filter]
target="imgs"
value=""

[[action]]
return="imgs"
[action.target]
key="imgs"
type="temp"
value=""
[action.operation]
key="imgs"
type="array_prefix"
value=","
[action.operation.option]
key="imagePath"
type="temp"
value=""
[action.after]
[action.after.filter]
target="imgs"
value=""
