[[action]]
return="database"
[action.operation]
key="database"
type="temporary"
value="gufengmh8_list"

[[action]]
return="url"
[action.target]
key="url"
type="string"
value="https://www.gufengmh8.com/manhua/woweicangsheng/"
[action.operation]
key="html"
type="download"
[action.after]
[action.after.transform]
target="html"
from="gbk"
to="utf8"
[action.after.replace]
target="html"
from="<img{^>}+src=\"({^\"}+)\"{^>}+data-original=\"({^\"}+)\">"
to="<img src=\"$1\" data-original=\"$2\">"


[[action]]
[action.target]
key="url"
type="temp"
[action.operation]
key="host"
type="url_host"

[[action]]
return="code"
[action.target]
key="url"
type="temp"
[action.operation]
key="code"
type="regex_get"
value="://\\w+\\.(\\w+)\\.\\w+"


[[action]]
[action.target]
key="html"
type="temp"
[action.operation]
key="dom"
type="dom_parser"


[[action]]
return="title"
[action.target]
key="dom"
type="temp"
[action.operation]
key="title"
type="dom_find"
value=".book-title h1"


[[action]]
return="number"
[action.target]
key="html"
type="temp"
[action.operation]
key="number"
type="regex_get"
value="comic\\.(\\d+)"

[[action]]
return="intro"
[action.target]
key="dom"
type="temp"
value=""
[action.operation]
key="intro"
type="dom_find"
value="#intro-all"


[[action]]
return="face"
[action.target]
key="dom"
type="temp"
[action.operation]
key="face"
type="dom_find"
value=".book-cover img"
[action.operation.option]
key="src"
type="attr"


[[action]]
return="pages"
[action.target]
key="dom"
type="temp"
[action.operation]
key="pages"
type="dom_find_all"
value="#chapter-list-1 li a"
[action.operation.option]
key="href"
type="attr"



[[action]]
return="pages"
[action.target]
key="pages"
type="temp"
value=""
[action.operation]
key="pages"
type="array_prefix"
value=","
[action.operation.option]
key="host"
type="temp"
[action.after]
[action.after.filter]
target="pages"
value=""

#
##将 return 的所有值, 放在 data中, post 给gateway的/submit
#[[action]]
#[action.target]
#key="gufengmh8_list"
#type="return"
#value=""
#[action.operation]
#key=""
#type="post"
#value="/submit"
#
##把 system 中的 token 放在 http 中的 header 中, key 为 token
#[action.operation.option]
#key="token"
#type="system"
#value="header"